- Check/Create self signed certificate for WebYaST

diff --git a/webyast/package/rcwebyast b/webyast/package/rcwebyast
--- a/webyast/package/rcwebyast
+++ b/webyast/package/rcwebyast
@@ -1,17 +1,17 @@
 #!/bin/sh
 #
 #     Copyright (C) 1995--2007  Marcus Rückert, SUSE / Novell Inc.
-#          
+#
 #     This library is free software; you can redistribute it and/or modify it
 #     under the terms of the GNU Lesser General Public License as published by
 #     the Free Software Foundation; either version 2.1 of the License, or (at
 #     your option) any later version.
-#			      
+#
 #     This library is distributed in the hope that it will be useful, but
 #     WITHOUT ANY WARRANTY; without even the implied warranty of
 #     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 #     Lesser General Public License for more details.
-#      
+#
 #     You should have received a copy of the GNU Lesser General Public
 #     License along with this library; if not, write to the Free Software
 #     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
@@ -23,10 +23,10 @@
 #
 #
 # LSB compatible service control script; see http://www.linuxbase.org/spec/
-# 
+#
 # Note: This template uses functions rc_XXX defined in /etc/rc.status on
 # UnitedLinux/SUSE/Novell based Linux distributions. If you want to base your
-# script on this template and ensure that it works on non UL based LSB 
+# script on this template and ensure that it works on non UL based LSB
 # compliant Linux distributions, you either have to provide the rc.status
 # functions from UL or change the script to work without them.
 # See skeleton.compat for a template that works with other distros as well.
@@ -42,10 +42,10 @@
 # Short-Description: webyast
 # Description:       Start webyast
 ### END INIT INFO
-# 
-# Any extensions to the keywords given above should be preceeded by 
+#
+# Any extensions to the keywords given above should be preceeded by
 # X-VendorTag- (X-UnitedLinux- X-SuSE- for us) according to LSB.
-# 
+#
 # Notes on Required-Start/Should-Start:
 # * There are two different issues that are solved by Required-Start
 #    and Should-Start
@@ -63,7 +63,7 @@
 #     in parallel). The tag Should-Start: is used for this.
 #     It tells, that if a service is available, it should be started
 #     before. If not, never mind.
-# * When specifying hard dependencies or ordering requirements, you can 
+# * When specifying hard dependencies or ordering requirements, you can
 #   use names of services (contents of their Provides: section)
 #   or pseudo names starting with a $. The following ones are available
 #   according to LSB (1.1):
@@ -79,15 +79,15 @@
 #   The $netdaemons pseudo service has been removed in LSB 1.2.
 #   For now, we still offer it for backward compatibility.
 #   These are new (LSB 1.2):
-#	$time			the system time has been set correctly	
+#	$time			the system time has been set correctly
 #	$portmap		SunRPC portmapping service available
 #   UnitedLinux extensions:
 #	$ALL			indicates that a script should be inserted
 #				at the end
-# * The services specified in the stop tags 
+# * The services specified in the stop tags
 #   (Required-Stop/Should-Stop)
 #   specify which services need to be still running when this service
-#   is shut down. Often the entries there are just copies or a subset 
+#   is shut down. Often the entries there are just copies or a subset
 #   from the respective start tag.
 # * Should-Start/Stop are now part of LSB as of 2.0,
 #   formerly SUSE/Unitedlinux used X-UnitedLinux-Should-Start/-Stop.
@@ -101,7 +101,7 @@
 # 0 - halt/poweroff 			6 - reboot
 # 1 - single user			2 - multiuser without network exported
 # 3 - multiuser w/ network (text mode)  5 - multiuser w/ network and X11 (xdm)
-# 
+#
 # Note on script names:
 # http://www.linuxbase.org/spec/refspecs/LSB_1.3.0/gLSB/gLSB/scrptnames.html
 # A registry has been set up to manage the init script namespace.
@@ -113,7 +113,7 @@
 # Check for missing binaries (stale symlinks should not happen)
 # Note: Special treatment of stop for LSB conformance
 NGINX_BIN=/usr/sbin/nginx
-test -x $NGINX_BIN || { echo "$NGINX_BIN not installed"; 
+test -x $NGINX_BIN || { echo "$NGINX_BIN not installed";
 	if [ "$1" = "stop" ]; then exit 0;
 	else exit 5; fi; }
 
@@ -125,8 +125,12 @@ test -r $NGINX_CONFIG || { echo "$NGINX_CONFIG not existing";
 
 PID_FILE=/var/run/webyast.pid
 
+CERTIFICATEFILE=/etc/nginx/certs/webyast.pem
+CERTKEYFILE=/etc/nginx/certs/webyast.key
+COMBINEDCERTFILE=/etc/nginx/certs/webyast-combined.pem
+
 # Source LSB init functions
-# providing start_daemon, killproc, pidofproc, 
+# providing start_daemon, killproc, pidofproc,
 # log_success_msg, log_failure_msg and log_warning_msg.
 # This is currently not used by UnitedLinux based distributions and
 # not needed for init scripts for UnitedLinux only. If it is used,
@@ -160,7 +164,7 @@ rc_reset
 # 6       - program is not configured
 # 7       - program is not running
 # 8--199  - reserved (8--99 LSB, 100--149 distrib, 150--199 appl)
-# 
+#
 # Note that starting an already running service, stopping
 # or restarting a not-running service as well as the restart
 # with force-reload (in case signaling is not supported) are
@@ -168,6 +172,19 @@ rc_reset
 
 case "$1" in
     start)
+    if [ ! -e  $COMBINEDCERTFILE ]
+    then
+        echo "No certificate found. Creating one now."
+        if ! /usr/sbin/check-create-certificate -c -C $CERTIFICATEFILE -K $CERTKEYFILE -B $COMBINEDCERTFILE -D webyast -O WebYaST -U WebYaST >/srv/www/webyast/log/check-create-certificate.log 2>&1
+        then
+            echo -n "Can not create certificate. Please see /srv/www/webyast/log/check-create-certificate.log for details."
+            rc_failed
+            rc_status -v
+            rc_exit
+        fi
+        chown nginx:nginx $CERTIFICATEFILE $CERTKEYFILE $COMBINEDCERTFILE
+    fi
+
        echo -n "Starting webyast "
   #generate deployment specific secret key (bnc#591345)
   SECRET=`cd /srv/www/webyast/ && rake -s secret`
@@ -189,6 +206,18 @@ case "$1" in
 
 	# Remember status and be verbose
 	rc_status -v
+
+       # print the URL of the server
+        if test "$?" -eq 0; then
+            IFC=`LC_ALL=C route | grep "^default" | tr -s " " | cut -d " " -f 8`
+            IP=`LC_ALL=C ifconfig $IFC | grep "inet addr" | cut -d ":" -f 2 | cut -d " " -f 1`
+            PORT=`LC_ALL=C grep "listen" $NGINX_CONFIG|cut -d ";" -f 1|tr -s " "|cut -d " " -f 3`
+            if [ -n "$IP" ]; then
+                echo -e "\t${done}The WebYaST client service is running at https://$IP:$PORT/${norm}\n"
+            else
+                echo -e "\t${warn}WebYaST could not determine the IP address for $IFC${norm}\n"
+            fi
+        fi
 	;;
     stop)
 	echo -n "Shutting down webyast "
@@ -249,7 +278,7 @@ case "$1" in
 	/sbin/killproc -HUP -p $PID_FILE $NGINX_BIN
 	#touch /var/run/webyast.pid
 	rc_status -v
-	
+
 	## Otherwise if it does not support reload:
 	#rc_failed 3
 	#rc_status -v
@@ -266,7 +295,7 @@ case "$1" in
 	# 3 - service not running (unused)
 	# 4 - service status unknown :-(
 	# 5--199 reserved (5--99 LSB, 100--149 distro, 150--199 appl.)
-	
+
 	# NOTE: checkproc returns LSB compliant status values.
 	/sbin/checkproc -p $PID_FILE $NGINX_BIN
 	# NOTE: rc_status knows that we called this init script with
@@ -286,3 +315,4 @@ case "$1" in
 	;;
 esac
 rc_exit
+
